name: EpicGuard
version: '${projectVersion}'
main: me.xneox.epicguard.bukkit.PlatformBukkit

author: xNeox
website: https://www.spigotmc.org/resources/72369/
description: Bot protection system for Minecraft servers.

commands:
  epicguard:
    description: Main plugin command.
    permission: epicguard.admin
    aliases: [ab, guard, eg, antibot]